module.exports = {
  LOGIN: "LOGIN",
  JOIN: "JOIN",
  PING: "PING",
  LEAVE: "LEAVE",
  DECLINE: "DECLINE",
  ACCEPT: "ACCEPT",
  CANCEL: "CANCEL",
  SELECT_USER: "SELECT_USER",
  SET_FILE: "SET_FILE",
  ADD_OUTGOING_REQUEST: "ADD_OUTGOING_REQUEST",
  RESET_CURRENT_MESSAGE: "RESET_CURRENT_MESSAGE",
  PROPOSE: "PROPOSE"
};
